### ISSUE TITLE
参加確定通知が団委員長宛にも欲しい

### ISSUE THREAD

**Issue by Radish-TR** [caffisenna/wbsc-entry#106]
### 概要

- 参加希望者へ参加確定通知が送信されると同時に団委員長宛にも送信して欲しい

### 現状

- 参加確定通知の受信を参加希望者へ直接確認する必要がある
- 参加希望者の連絡先不明時は隊長経由で確認する必要がある

### 目的

- 団として参加申込状況を最終確認するため

**Comment by caffisenna** [comment]
@Radish-TR 
ご提案ありがとうございます!
AIS委員会に提案させていただき、改修案に盛り込むか検討を依頼致します。

**Comment by caffisenna** [comment]
改修案:
- 団委員長の承認時に、以降の通知を受け取るか否かチェック欄を設ける
